apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: gcr.io/your-project-id/spring-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://<INSTANCE_CONNECTION_NAME>:3306/yourdatabase
        - name: SPRING_DATASOURCE_USERNAME
          value: youruser
        - name: SPRING_DATASOURCE_PASSWORD
          value: yourpassword
